"""中文 → 英文常见食物名映射。

USDA 数据库仅支持英文查询，这里把中文条目映射为简短的核心英文词。
我们的重排器会把带 "raw" 的原料/生鲜条目优先展示，所以映射值一般只需一个核心关键词即可。
"""
from __future__ import annotations

ZH_TO_EN: dict[str, str] = {
    # 水果
    "香蕉": "banana",
    "苹果": "apple",
    "橙子": "orange",
    "橘子": "tangerine",
    "柠檬": "lemon",
    "葡萄": "grapes",
    "草莓": "strawberry",
    "蓝莓": "blueberry",
    "西瓜": "watermelon",
    "梨": "pears",
    "桃": "peaches",
    "桃子": "peaches",
    "芒果": "mango",
    "菠萝": "pineapple",
    "凤梨": "pineapple",
    "猕猴桃": "kiwifruit",
    "奇异果": "kiwifruit",
    "樱桃": "cherries",
    "牛油果": "avocado",
    "鳄梨": "avocado",
    "哈密瓜": "cantaloupe",
    "木瓜": "papaya",
    "石榴": "pomegranate",
    "椰子": "coconut",
    "榴莲": "durian",
    "荔枝": "lychee",
    "龙眼": "longan",
    "桂圆": "longan",
    "柚子": "pomelo",
    "李子": "plum",
    "杏": "apricot",
    "无花果": "figs",
    "枣": "jujube",
    # 蔬菜
    "西红柿": "tomato",
    "番茄": "tomato",
    "黄瓜": "cucumber",
    "胡萝卜": "carrot",
    "土豆": "potato",
    "马铃薯": "potato",
    "红薯": "sweet potato",
    "地瓜": "sweet potato",
    "白菜": "chinese cabbage",
    "大白菜": "chinese cabbage",
    "卷心菜": "cabbage",
    "菠菜": "spinach",
    "西兰花": "broccoli",
    "花椰菜": "cauliflower",
    "生菜": "lettuce",
    "芹菜": "celery",
    "洋葱": "onion",
    "大蒜": "garlic",
    "生姜": "ginger",
    "茄子": "eggplant",
    "青椒": "peppers sweet green",
    "甜椒": "peppers sweet",
    "辣椒": "peppers hot",
    "南瓜": "pumpkin",
    "玉米": "corn sweet",
    "蘑菇": "mushrooms",
    "香菇": "shiitake",
    "豆芽": "mung bean sprouts",
    "豆角": "beans snap",
    # 肉类 / 蛋类 / 海鲜
    "鸡肉": "chicken",
    "鸡胸": "chicken breast raw",
    "鸡胸肉": "chicken breast raw",
    "鸡腿": "chicken thigh raw",
    "牛肉": "beef raw",
    "猪肉": "pork raw",
    "羊肉": "lamb raw",
    "鱼": "fish raw",
    "三文鱼": "salmon raw",
    "鲑鱼": "salmon raw",
    "金枪鱼": "tuna raw",
    "吞拿鱼": "tuna raw",
    "鳕鱼": "cod raw",
    "虾": "shrimp raw",
    "螃蟹": "crab raw",
    "鸡蛋": "egg whole raw",
    "蛋": "egg whole raw",
    "鸭蛋": "duck egg",
    # 奶制品
    "牛奶": "milk whole",
    "全脂牛奶": "milk whole",
    "脱脂牛奶": "milk nonfat",
    "酸奶": "yogurt plain",
    "奶酪": "cheese cheddar",
    "芝士": "cheese cheddar",
    "黄油": "butter",
    "奶油": "cream",
    # 主食 / 豆类 / 坚果
    "米饭": "rice white cooked",
    "大米": "rice white raw",
    "稻米": "rice white raw",
    "白米": "rice white raw",
    "糙米": "rice brown",
    "面条": "noodles cooked",
    "意大利面": "pasta cooked",
    "面包": "bread white",
    "全麦面包": "bread whole wheat",
    "馒头": "steamed bun",
    "燕麦": "oats",
    "燕麦片": "oats",
    "小麦": "wheat",
    "豆腐": "tofu raw",
    "黄豆": "soybeans raw",
    "大豆": "soybeans raw",
    "豆浆": "soy milk",
    "红豆": "red beans",
    "绿豆": "mung beans",
    "花生": "peanuts raw",
    "核桃": "walnuts",
    "杏仁": "almonds",
    "腰果": "cashews",
    "开心果": "pistachios",
    "葵花籽": "sunflower seeds",
    # 饮品 / 其他
    "咖啡": "coffee brewed",
    "绿茶": "green tea",
    "红茶": "black tea",
    "可乐": "cola",
    "橙汁": "orange juice",
    "蜂蜜": "honey",
    "糖": "sugar",
    "盐": "salt",
    "橄榄油": "olive oil",
    "食用油": "vegetable oil",
    "巧克力": "chocolate dark",
    "冰淇淋": "ice cream vanilla",
    "薯条": "french fries",
    "披萨": "pizza",
}


def to_english(query: str) -> str:
    """查字典；找不到就原样返回。"""
    q = (query or "").strip()
    return ZH_TO_EN.get(q, q)


def has_chinese(text: str) -> bool:
    return any("\u4e00" <= ch <= "\u9fff" for ch in text or "")
